


module ensembles 

    use interp1D 
    use ncio 

    implicit none 


    double precision, parameter :: mv = -9999.d0




    private 
    public :: ens_init_1D

contains 




    subroutine ens_1D(ens_fldr,fldrs,filename,name,time)

        implicit none 

        character(len=*), intent(IN) :: ens_fldr, fldrs(:), filename 
        character(len=*), intent(IN) :: name
        double precision, intent(IN) :: time(:) 

        character(len=512) :: filename_out 

        ! Define output ensemble filename 
        filename_out = "ens_"//trim(filename)


        return 

    end subroutine ens_1D


    subroutine ens_init_1D(ens_fldr,filename,names,units,time,tunits,nsim)

        implicit none 

        character(len=*), intent(IN) :: ens_fldr, filename
        character(len=*), intent(IN) :: names(:), units(:), tunits
        double precision, intent(IN) :: time(:)
        integer :: nsim

        character(len=512) :: filename_out, path_out 
        integer :: nvar, q 


        ! Define output ensemble filename 
        filename_out = "ens_"//trim(filename)
        path_out     = trim(ens_fldr)//"/"//trim(filename_out)

        nvar = size(names)

        call nc_create(path_out,description="Generated by ensembles module.")
        call nc_write_dim(path_out,"sim",x=1,dx=1,nx=nsim)
        call nc_write_dim(path_out,"time",x=time,units=tunits,calendar="360_day",unlimited=.TRUE.)

        do q = 1, nvar 
            call nc_write(path_out,names(q),mv,dim1="sim",dim2="time", &
                          units=units(q),missing_value=mv,start=[1,1],count=[1,1])
        end do 

        return 

    end subroutine ens_init_1D 


    subroutine ens_folders()

        implicit none 

        return 

    end subroutine ens_folders

end module ensembles 