


module ensembles 

    use interp1D 
    use ncio 

    implicit none 


    double precision, parameter :: mv = -9999.d0




    private 
    public :: ens_init

contains 




    subroutine ens_1D(ens_fldr,fldrs,filename,name,time)

        implicit none 

        character(len=*), intent(IN) :: ens_fldr, fldrs(:), filename 
        character(len=*), intent(IN) :: name
        double precision, intent(IN) :: time(:) 

        character(len=512) :: filename_out 

        ! Define output ensemble filename 
        filename_out = "ens_"//trim(filename)


        return 

    end subroutine ens_1D


    subroutine ens_init(ens_fldr,filename,nsim,x,xname,xunits, &
                        y,yname,yunits,z,zname,zunits,t,tname,tunits)

        ! This subroutine will initialize an ensemble file of up to four dimensions
        ! (3 dimensions + 1 time dimension)

        implicit none 

        character(len=*), intent(IN) :: ens_fldr, filename
        integer :: nsim

        double precision, intent(IN), optional :: x(:) 
        character(len=*), intent(IN), optional :: xname, xunits 
        
        double precision, intent(IN), optional :: y(:) 
        character(len=*), intent(IN), optional :: yname, yunits 
            
        double precision, intent(IN), optional :: z(:) 
        character(len=*), intent(IN), optional :: zname, zunits 
        
        double precision, intent(IN), optional :: t(:) 
        character(len=*), intent(IN), optional :: tname, tunits 
        
        character(len=512) :: filename_out, path_out 
        integer :: nvar, q 


        ! Define output ensemble filename 
        filename_out = "ens_"//trim(filename)
        path_out     = trim(ens_fldr)//"/"//trim(filename_out)

        call nc_create(path_out,description="Generated by ensembles module.")
        call nc_write_dim(path_out,"sim",x=1,dx=1,nx=nsim)

        if (present(x)) then 
            if (.not. present(xname) .or. .not. present(xunits)) then 
                write(*,*) "ens_init_temporal:: error: To define x dimension, name and units are needed."
                stop 
            end if 

            call nc_write_dim(path_out,xname,x=x,units=xunits)

        end if 

        if (present(y)) then 
            if (.not. present(yname) .or. .not. present(yunits)) then 
                write(*,*) "ens_init_temporal:: error: To define y dimension, name and units are needed."
                stop 
            end if 

            call nc_write_dim(path_out,yname,x=y,units=yunits)

        end if 

        if (present(z)) then 
            if (.not. present(zname) .or. .not. present(zunits)) then 
                write(*,*) "ens_init_temporal:: error: To define z dimension, name and units are needed."
                stop 
            end if 

            call nc_write_dim(path_out,zname,x=z,units=zunits)

        end if 

        if (present(t)) then 
            if (.not. present(tname) .or. .not. present(tunits)) then 
                write(*,*) "ens_init_temporal:: error: To define time dimension, name and units are needed."
                stop 
            end if 

            call nc_write_dim(path_out,tname,x=t,units=tunits,calendar="360_day",unlimited=.TRUE.)

        end if 

        return 

    end subroutine ens_init

!         do q = 1, nvar 
!             call nc_write(path_out,names(q),mv,dim1="sim",dim2=xname,dim3="time", &
!                           units=units(q),missing_value=mv,start=[1,1,1],count=[1,1,1])
!         end do 


    subroutine ens_folders()

        implicit none 

        return 

    end subroutine ens_folders

end module ensembles 